# -*- coding: utf-8 -*-
"""breasKVis_data_extraction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OofITQW9qRiNBmWyHp6Mmw01wRBXpOMP
"""

!sudo add-apt-repository -y ppa:alessandro-strada/ppa 2>&1 > /dev/null
!sudo apt-get update -qq 2>&1 > /dev/null
!sudo apt -y install -qq google-drive-ocamlfuse 2>&1 > /dev/null
!google-drive-ocamlfuse

# Commented out IPython magic to ensure Python compatibility.
!sudo apt-get install -qq w3m # to act as web browser 
!xdg-settings set default-web-browser w3m.desktop # to set default browser
# %cd /content
!mkdir drive
# %cd drive
!mkdir MyDrive
# %cd ..
# %cd ..
!google-drive-ocamlfuse /content/drive/MyDrive

import os
import numpy as np
import cv2

data_dir_benign = '/content/drive/MyDrive/Datasets/breaKVis/benign/SOB'
data_dir_malignant = '/content/drive/MyDrive/Datasets/breaKVis/malignant/SOB'

def extract_images(path, sizex, sizey):
  data = []
  folders = sorted(os.listdir(path))
  for folder in folders:
    for final_folder in os.listdir(os.path.join(path, folder)):
      for file in os.listdir(os.path.join(path, folder, final_folder)):
        mat_file = cv2.imread(os.path.join(path, folder, final_folder, file))
        data.append(cv2.resize(mat_file, (sizex, sizey)))
    print(np.array(data).shape)
  return np.array(data)

benign_folders = os.listdir(data_dir_benign)
malignant_folders = os.listdir(data_dir_malignant)
sizex, sizey = 224, 224

print(f' Resizing the image resolution to: {sizex, sizey}')

# All benign types
print(f'Extracting benign data at {data_dir_benign}')
print(f'Extracting images for {benign_folders[0]}')
print(f'Full path is {os.path.join(data_dir_benign, benign_folders[0])}')
fibroadenoma_dir = os.path.join(data_dir_benign, benign_folders[0])
fibroadenoma = extract_images(fibroadenoma_dir, sizex, sizey)

print(f'Extracting images for {benign_folders[1]}')
print(f'Full path is {os.path.join(data_dir_benign, benign_folders[1])}')
tubular_adenoma_dir = os.path.join(data_dir_benign, benign_folders[1])
tubular_adenoma = extract_images(tubular_adenoma_dir, sizex, sizey)

print(f'Extracting images for {benign_folders[2]}')
print(f'Full path is {os.path.join(data_dir_benign, benign_folders[2])}')
phyllodes_tumor_dir = os.path.join(data_dir_benign, benign_folders[2])
phyllodes_tumor = extract_images(phyllodes_tumor_dir, sizex, sizey)

print(f'Extracting images for {benign_folders[3]}')
print(f'Full path is {os.path.join(data_dir_benign, benign_folders[3])}')
adenosis_dir = os.path.join(data_dir_benign, benign_folders[3])
adenosis = extract_images(adenosis_dir, sizex, sizey)


# All malignant types
print(f'Extracting malignant data at {data_dir_malignant}')
print(f'Extracting images for {malignant_folders[0]}')
print(f'Full path is {os.path.join(data_dir_malignant, malignant_folders[0])}')
ductal_carcinoma_dir = os.path.join(data_dir_malignant, malignant_folders[0])
ductal_carcinoma = extract_images(ductal_carcinoma_dir, sizex, sizey)

print(f'Extracting images for {malignant_folders[1]}')
print(f'Full path is {os.path.join(data_dir_malignant, malignant_folders[1])}')
papillary_carcinoma_dir = os.path.join(data_dir_malignant, malignant_folders[1])
papillary_carcinoma = extract_images(papillary_carcinoma_dir, sizex, sizey)

print(f'Extracting images for {malignant_folders[2]}')
print(f'Full path is {os.path.join(data_dir_malignant, malignant_folders[2])}')
lobular_carcinoma_dir = os.path.join(data_dir_malignant, malignant_folders[2])
lobular_carcinoma = extract_images(lobular_carcinoma_dir, sizex, sizey)

print(f'Extracting images for {malignant_folders[3]}')
print(f'Full path is {os.path.join(data_dir_malignant, malignant_folders[3])}')
mucinous_carcinoma_dir = os.path.join(data_dir_malignant, malignant_folders[3])
mucinous_carcinoma = extract_images(mucinous_carcinoma_dir, sizex, sizey)